### ISSUE TITLE
Switching to the latest version of Allegro or to SDL2

### ISSUE THREAD

**Issue by ghost** [OnlineCop/kq-fork#3]
KQ currently need Allegro 4 to compile, it should use a modern library instead.

**Comment by peterhull90** [comment]
I wonder, did you ever look at cocos2d-x? It has built-in support for Tiled maps and Lua. I haven't used it myself apart from a quick look but it seems to be well supported and under active development.

**Comment by peterhull90** [comment]
I've had a look at this. It's going to be tricky to *convert* the current code. Allegro 4 allows you to draw whenever you want and wait for key input whenever you like, whereas SDL2 ideally has an event loop structure.

I'd prefer to do it properly, which I think will need quite a fairly wide-ranging rewrite. Any thoughts?

ps. Allegro 5 is more like SDL2 than Allegro 4, so a rewrite to Allegro 5 wouldn't be any easier.

**Comment by OnlineCop** [comment]
SDL or Allegro5 would both be a fairly significant code change. That's one of the loftier goals that would affect most every function in every file. I'd put this onto the backburner just until we can get everything a bit more OO.

**Comment by peterhull90** [comment]
I am creeping towards this one. My current activity is to remove all uses of Allegro dat files. I can see how I might convert the drawing and sound code, not sure about the event loop side of things yet.

**Comment by pedro-w** [comment]
Just by coincidence I was looking at sourceforge today for the first time in ages. The old kqlives project is there just as we left it and I was feeling nostalgic! Converting to SDL2 seems a good idea, I look forward to seeing what comes out of it. I was less impressed that @phinjensen seems to have deleted the copyright/ license stuff from his fork, what was that all about?

**Comment by OnlineCop** [comment]
Wow, I totally forgot about the old code on SourceForge (I see commits from 20 years ago! Whaaaaa?).

As far as I'm aware, there has never really been a game resolution, has there? Like, we never designed an end boss or tied up all the side quests?

I wonder if we should revive JB's original storyline, or just hash out the remainder of the game once we can get it to work with SDL2?

**Comment by z9484** [comment]
I have been gathering graphics replacements and brainstorming a suitable epic ending. Though my plans are in some ways a rewrite because it would change a number of things that don't make sense. For example you cannot get through the gate near Andra because of a civil war. Once you get on the other side, the civil war is never mentioned. I think it would make more sense if Malkaron's forces had more of an impact on the world. The Oracle's area could have fallen into chaos because of Malkaron's earlier expeditions. (he was marauding for years IIRC).

**Comment by phinjensen** [comment]
@pedro-w If I did remove some copyright or license stuff from my fork, it was accidental. Honestly, the state of my fork a mess as I've figured stuff out so what I have right now is probably completely unhelpful at the moment. If/when I move things far enough along to be merged back into this repo, I'll make sure to clean things up as much as possible.

**Comment by teamterradactyl** [comment]
OnlineCop just pinged me and told me to check my email.

Hey Peter and all! It’s been... wow, a while.

I’m not sure I’ve got a computer old enough to still run the original. I
might need to run it in a VM just to remember what the game was about.

Where did my mapedit program get moved to? I don’t see it, or an I just
stupid?

-TeamTerradactyl

**Comment by z9484** [comment]
I'm not as worried about the plot or the graphics as the state of the engine. I would work on the plot and scripts more but I find it discouraging as when I get KQ to actually compile then it is in more broken state than it was in the sourceforge days. (no offense to your work on the c++ port, but some bugs got added in along the way. Getting rid of the allegro data files and switching to tmx maps work great though.) 

A while ago I tried playing around with adding high resolution portraits but the limited palette really gets in the way of that.

Does anyone have any ideas how you would convert the lua scripts to work with an event loop architecture? I've done something similar with pygame but it required a second thread that sent over events to the game loop. So that the map script can be blocked in the middle of a conversation waiting for the game loop to return an event of what dialogue choice they picked. But that added complexity is a little hard to make work perfectly.

To be honest I'm a little bit surprised the original worked as well as it does, because every lua command has to also call blit screen, update animations, read input, etc. Having a gameloop and game state manager is a lot easier to manage, but has the disadvantage of making scripted events hard to keep in sync with the action on screen. Well at least in my experience. I keep wondering if there is an easy solution that I'm missing.  Conversation logic can be converted to decision trees, but I really enjoyed the serial nature of the lua script logic as it was really easy to jump into, even if you are intimidated by programming c/c++, as you can easily see the flow of the scenes. I actually started working on Kqthebetrayer before I learned how to program. =)

**Comment by z9484** [comment]
The majority of the graphics, music, and probably the sounds effects are just rips from commercial games so unfortunately we can't legally use them. The engine being replaced doesn't change anything in my opinion, a number of commercial games have rereleases with new engines look at the latest Dragon Quest game. But you do have a point about the storyline. I have been thinking about the storyline but my plot ideas are quite a bit of a departure so I had been just thinking about releasing my own under a new name and a new python engine(because kqlives engine development had stalled) called KQ Reborn or something.

**Comment by OnlineCop** [comment]
I set up a Discussions and a Wiki on this repo. I haven't had much time to write anything into them yet, so they're still empty.

@phinjensen I checked out your SDL2 fork and tried to compile it on Windows. Specifically:

1. On Windows 10, I created a new user account (to try to give as fresh a start as possible): `kqlives`
2. I (re)installed WSL and installed a WSL:Ubuntu distro.
3. I installed vscode and checked out your repo (to C:\Users\kqlives\Documents\phinjensen\kq-fork)
4. Within vscode, I opened WSL:Ubuntu and had updated/installed a bunch of stuff via `apt-get` (a lot of the `apt install ...` came from trial-and-error and are simply sorted alphabetically below):
    1. `apt update`
    2. `apt upgrade`
    3. `apt install autoconf build-essential clang cmake cmake-doc freeglut3-dev libasound2-dev libgl-dev libpng-dev libpulse-dev libsdl2-dev libtinyxml-dev libtinyxml-dev libtinyxml-doc libtinyxml2-dev libxi-dev libxmu-dev manpages-dev ninja-build python python3-pip python3.9 tinyxml2 xorg-dev`
5. I installed [SDL_image](https://libsdl.org/projects/SDL_image/) and [SDL_mixer](https://libsdl.org/projects/SDL_mixer/) from the .tar.gz sources since I couldn't find an `apt-get install` for those two.
6. I created a `build` directory to run cmake from: `mkdir -p phinjensen/kq-fork/build/ && cd phinjensen/kq-fork/build`.
7. Running `cmake ..` from the build directory didn't seem to have any errors.
8. Running `make -j$(nproc)` gave several warnings, but it still created a `kq-fork` binary in the root project directory.
9. Running the `kq-fork` binary gave all sorts of errors (some of the attempts to fix them include packages in the above `apt install ...`).

Is there a specific configuration I need to do in order to get this to run? Should I scrap WSL and try to run/install SDL2 natively in Windows? Are you using vscode, Visual Studio, or another IDE/compiler?
